### ISSUE TITLE
User ORM

### ISSUE THREAD

**Issue by benjaminkao** [sfsu-csc-667-spring-2021-roberts/term-project-team-aaby#11]
- Using the general Database Query API, create a data structure model of the User table.
- Create methods to get users and insert users.
- These methods should also convert the data retrieved from the database into an easily readable/accessible data structure.

For example:
class User {
  userID;
  firstName;
  lastName;
  email;
  password;

  factory getUser(userID) {
    // Get user data from database
    // Set all data fields here
  }

  function insertUser() {
   // Use data fields to insert a new user row into database
  }

}

**Comment by Doxify** [comment]
Gonna assign this to myself since im already working on implementing passport

**Comment by Doxify** [comment]
Shooting to get this done before tonight's meeting btw @benjaminkao

**Comment by Doxify** [comment]
Completed.
